index.js

MS Edge and IE 11 have issues with SVGs whereby they make them tabbable even if their containing element has a `tabindex` of `-1 `or isn't even tabbable at all.
Adding `focusable="false"` and `tabindex="-1"` usually solves this, but `tabbable` is incorrectly adding them to its list of `tabbables`.
Calling `candidate.tabIndex` on an SVG returns `undefined`, but using `getAttribute('tabindex')`works fine.
This PR provides this as a fallback.

Add alternative for obtaining tabIndex for SVGs

---

index.js
test/tabbable.test.js

On some browsers (Chrome specifically) Array.prototype.sort is not stable. This causes the order of like-tabindexed elements to be unexpected in some cases.
By comparing the array index of elements from the querySelectorAll, we can tie-break elements with the same tabindex.

Use original dom position index to stabilize sort func

---

README.md
index.js
test/tabbable.test.js

Here is PR for #14.
Uses [matches](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches) and [some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) both support IE9.

Add includeContainer option

---

index.js
test/tabbable.test.js

#13 broke `tabbable(document)` since `ownerDocument` is `null` on all document nodes.[1] This PR fixes that calling pattern
[1]: https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument

Fix crash when tabbable called with document

---

index.js

All major browsers accept array as `querySelectorAll` argument, but this isn't actually documented nor present in specifications
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/querySelectorAll/#Syntax)
> `selectors` is a string containing one or more CSS selectors separated by commas.
[Selectors API spec](https://dev.w3.org/2006/webapi/selectors-api2/#interface-definitions)
[DOM spec](https://www.w3.org/TR/dom/#interface-parentnode)
>```
>NodeList  querySelectorAll(DOMString selectors);
>```
Currently it makes impossible to use tabbable and [dom4 polyfill](https://github.com/WebReflection/dom4) in one project, as it relies on `querySelectorAll` argument being a string

Use the documented `querySelectorAll` signature

---

index.js

Since there's no `Element` global in Node.js, it's not safe to assume that `Element.prototype` exists. Looks like this broke in 3.0.0.
Tabbable isn't actually useful in server-side code, but universal React components may still end up loading Tabbable via focus-trap-react when rendering on the server.

Fix `ReferenceError: Element is not defined` in Node.js

---

index.js
test/tabbable.test.js

In Web Components, the root element is a document fragment rather than an `<html>` element.
Fixes #34 and https://github.com/material-components/material-components-web/issues/4131

Fix error when element is inside a Shadow DOM

---

.travis.yml
index.js
test/fixtures/shadow-dom.html
test/tabbable.test.js

This is taking over #32, fixing conflicts with newer changes.
This change is not only simplifying the code. It is also optimizing it a lot. When running focus-trap on an element containing a thousand checboxes (and a few other tabbable items), `updateTabbableNodes` (which is mostly a call to `tabbable`) went from 945ms to 15ms (on a rather powerful desktop browser).

Optimize and simplify the function to test for visibility

---

README.md
rollup.config.js
src/index.js
test/tabbable.test.js

**Why?**
Improving tree-shakeability of this package. Usage of static properties like this usually retains the containing object (in this case a function) even if it stays unused. This matters when `tabbable` is being used as transitive dep.
Partially fixes #39 
⚠️ this is a breaking change

Change public exports shape

---

.changeset/blue-lions-wink.md
index.d.ts

Please verify this but I believe that the change is correct - it seems that the raw `Element` interface doesn't have `focus()` method on it. That method comes from `HTMLOrSVGElement` which both `HTMLElement` and `SVGElement` extend.

The TypeScript return type of `tabbable` has been changed from `Array<Element>` to `Array<HTMLElement | SVGElement>`

---

.changeset/proud-nails-smoke.md
babel.config.js
package.json
rollup.config.js

Fixes #96
Also targets ESM browsers for the ESM build, rather than ES5 browsers
for the other builds.

Transpile non-minified bundles

---

.changeset/healthy-ravens-pump.md
README.md
src/index.js
test/fixtures/details.html
test/tabbable.test.js

This PR fixes some issues with the details/summary elements:
1. ignore elements nested under a closed details element with the exception of the first summary element.
2. ignore any summary elements except the first.
3. pickup details elements as tabbable in case they don't have any summary.
- ~Issue being fixed is referenced.~
- ~Typings added/updated.~
- ~Changes to dependencies explained.~

Details and summary element fixes

---

.changeset/lucky-pots-add.md
src/index.js

This PR replaces the direct call to `element.matches` with the fallback for IE11 & Webkit5 where missing.
Fixes #156

use matches fallback everywhere

---

.changeset/soft-days-invite.md
README.md
package.json
src/index.js
test/fixtures/radio.html
test/tabbable.test.js
yarn.lock

Fixes #168.  Uses `CSS.escape` to escape special characters in the radio button `name` attribute when constructing the selector here:
<https://github.com/focus-trap/tabbable/blob/cd06b988e9b1924405ba406c1a503046af2687a2/src/index.js#L105>
Also adds a caveat to the documentation about requiring a polyfill for `CSS.escape` when running on IE.

Escape CSS selector special characters in radio button names

---

.changeset/shy-ladybugs-kneel.md
README.md
index.d.ts
src/index.js
test/fixtures/displayed.html
test/fixtures/index.js
test/focusable.test.js
test/helpers.js
test/isFocusable.test.js
test/isTabbable.test.js
test/tabbable.test.js

This PR adds the ability to configure how an element is checked for display. The default behavior is kept as it was, with 2 additional options for an alternative size based check and an opt out option added.
The option `displayCheck` is added to all 4 checking methods of Tabbable.
In order to check the size based option, `getBoundingClientRect` had to be mocked, since Tabbable is checked using jsdom and no longer checked against a real browser. I think this is a miss (I certainly missed this move in the refactor) and we should consider moving back to actual browser testing (against multiple browsers) as this library is trying to integrate with low level browser APIs and mimic browser behavior. 
<details>
<br/>
- Source changes maintain stated browser …

display check configuration

---

cypress/plugins/index.js
package.json
test/e2e/focusable.e2e.js
test/e2e/isFocusable.e2e.js
test/e2e/isTabbable.e2e.js
test/e2e/tabbable.e2e.js
test/fixtures/displayed.html

Testing how to move forward with web components I found some leftovers:
- removes leftovers mocks and markers for JSDOM
- generates coverage and insert code instrumentation just when coverage needs to be collected - I missed the fact that  in addition to creating coverage every time a test run, it caused debugging to be annoying with extra step throughs over each line.
<details>
<br/>
- ~~Issue being fixed is referenced.~~
- ~~Unit test coverage added/updated.~~
- E2E test coverage updated.
- ~~Typings added/updated.~~
- ~~README updated (API changes, instructions, etc.).~~
- ~~Changes to dependencies explained.~~
- ~~Changeset added~~
</details>

browser testing cleanups

---

.github/workflows/ci.yml

Firefox may hang in CI when running Cypress tests. Increasing shared memory helps to avoid this. Also added timeout just to be sure since default is 6 hours, which unnecessarily burns CI minutes.

Avoid FF hang

---

CHANGELOG.md
README.md
index.d.ts
src/index.js
test/debug.js
test/e2e/e2e.helpers.js
test/e2e/focusable.e2e.js
test/e2e/shadow-dom.e2e.js
test/e2e/tabbable.e2e.js
test/fixtures/index.js
test/fixtures/shadow-dom-display.html
test/fixtures/shadow-dom-query.html
test/fixtures/shadow-dom-radio.html
test/fixtures/shadow-dom.html
test/shadow-root-utils.js

This PR adds support for shadow dom (as requested in #50). Currently I just placed all tests in a single e2e spec, because it was much easier to handle, I will probably break it down into the 4 apis before we merge. The code is separated into 2 parts:
1. changes to check isTabbable/isFocusable
2. alternative to dom query which walks the dom 
new options API:
- getShadowRoot(element): called for any element without `shadowRoot` property in order to detect shadow dom. (return `shadowRoot` in order to query internally, `true` to indicate there is a shadow-root, but it's not available or `false` for no shadow-root)
- add development shadow-root-utils to handle hydration, polyfill and expose closed shadow root for tests.
- add options to render a subtree of a fixture `setupFixture(content, …

shadow dom support

---

.changeset/breezy-grapes-flash.md
src/index.js

Made `isDisabledFromFieldset` a bit more concise and readable.  
The regex may even be faster than the multiple conditions, since they access `node.tagName` multiple times.
Since the changes are by no means necessary, I am opening just a Draft pull request. Let me know what you think.
PS: I did not refactor your code just for fun, I am working on a project in which I reuse *tabbable*'s code and happened to refactor this block.
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` …

refactor(index.js): Made "isDisabledFromFieldset" a bit more concise

---

.changeset/long-planets-sleep.md
src/index.js
test/e2e/isFocusable.e2e.js
test/e2e/isTabbable.e2e.js
test/fixtures/fieldset.html

As noted in #596  `isDisabledFromFieldset` wasn't checking whether the disabled `<fieldset>` containing `node` is the top-most disabled `<fieldset>`. Now it does 🎉
Fixes #596
Note: I have no idea if there are tests for the case in which a form field is nested in the first `<legend>` of a disabled `<fieldset>` being nested in another disabled `<fieldset>`. If there are such tests, they need to be fixed too.
Edit: It looks like there are no such tests. There are no disabled `<fieldset>`s nested in another disabled `<fieldset>` in the structure of [fieldset.html](https://github.com/focus-trap/tabbable/blob/master/test/fixtures/fieldset.html). Should I add such a test?
<details>
<br/>
- Source changes maintain stated …

fix(index.js): fixed bug in 'isDisabledFromFieldset' (fixes #596)

---

.changeset/hip-tomatoes-hug.md
src/index.js
test/e2e/focusable.e2e.js
test/e2e/isFocusable.e2e.js
test/e2e/isTabbable.e2e.js
test/e2e/tabbable.e2e.js
test/fixtures/displayed.html

Optimized `displayCheck: "full"` by replacing [this DOM traversal](https://github.com/focus-trap/tabbable/blob/7609e9ecf47941a2b69aab2149e8760ea1f7392e/src/index.js#L154) (executed on every potential focusable element) with the following statement:
```javascript
return !node.getClientRects().length;
```
which is a more general check for whether an elements has display boxes. `display: "none"` is only a special case of `!node.getClientRects().length`.
Another case of elements with no display boxes would be elements with `display: "contents"`. And (since this case wasn't previosly handled) tests have been added to cover this possibility.
Fixes #592
<details>
<br/>
- Source changes maintain stated browser …

Optimizing `displayCheck: "full"`

---

test/e2e/focusable.e2e.js
test/e2e/isFocusable.e2e.js
test/e2e/isTabbable.e2e.js
test/e2e/tabbable.e2e.js
test/fixtures/radio.html

Can't repro the issue, but might as well keep the test since we
seem to like fieldsets but not forms for some reason.
<details>
<br/>
- Changeset added (run `yarn changeset` locally to add one, and follow the prompts).
- EXCEPTION: A Changeset is not required if the change does not affect any of the source …

[#632] Add test for radios in a form

---

.changeset/happy-zebras-attend.md
.changeset/shadow-root.md
CHANGELOG.md
README.md
cypress/plugins/index.js
index.d.ts
package.json
src/index.js
test/debug.js
test/e2e/e2e.helpers.js
test/e2e/focusable.e2e.js
test/e2e/isFocusable.e2e.js
test/e2e/isTabbable.e2e.js
test/e2e/shadow-dom.e2e.js
test/e2e/tabbable.e2e.js
test/fixtures/basic.html
test/fixtures/displayed.html
test/fixtures/index.js
test/fixtures/radio.html
test/fixtures/shadow-dom-display.html
test/fixtures/shadow-dom-query.html
test/fixtures/shadow-dom-radio.html
test/fixtures/shadow-dom.html
test/shadow-root-utils.js

👉  __See #304 for initial PR and discussion history__
This PR adds support for shadow dom (as requested in #50). Currently I just placed all tests in a single e2e spec, because it was much easier to handle, I will probably break it down into the 4 apis before we merge. The code is separated into 2 parts:
1. changes to check isTabbable/isFocusable
2. alternative to dom query which walks the dom 
new options API:
- getShadowRoot(element): called for any element without `shadowRoot` property in order to detect shadow dom. (return `shadowRoot` in order to query internally, `true` to indicate there is a shadow-root, but it's not available or `false` for no shadow-root)
- add development shadow-root-utils to handle hydration, polyfill and expose closed shadow root for tests.
- add options to …

Shadow DOM support (v5.3.0)

---

README.md

This PR adds a workaround to enable using tabbable in JSdom environment.

Include Jsdom workaround in readme

---

.changeset/swift-jeans-roll.md
README.md
src/index.js
test/e2e/e2e.helpers.js
test/e2e/focusable.e2e.js
test/e2e/isFocusable.e2e.js
test/e2e/isTabbable.e2e.js
test/e2e/shadow-dom.e2e.js
test/e2e/tabbable.e2e.js
test/fixtures/basic.html

Fixes #664
There are legitimate cases where tabbable's APIs are expected to work on container
nodes that are not actually attached to the document. The result is that the
`getClientRects()` API never returns any rects for visible nodes, resulting in
tabbable thinking ALL nodes in the container are hidden.
__NOTE:__ Assuming the node is visible under the default/legacy "full" mode
when the node is __not__ in the document is actually the legacy behavior.
When a node is detached, `getComputedStyle(node).display` is always
`undefined` and our checks were explicitly verifying if
`getComputedStyle(node).display === 'none'` to conclude a node was
hidden, which means this check would fail and we could conclude the
node was __visible__ even if it was not.
<details> …

[#664] Assume node is visible when displayCheck=full if node not in document

---

.all-contributorsrc
.changeset/violet-mugs-whisper.md
README.md
src/index.js
test/e2e/shadow-dom.e2e.js
test/fixtures/index.js
test/fixtures/shadow-dom-untabbable.html

A browser will skip tab-targeting an element if it is the only child of a web component which has a tabindex of -1.
```html
<my-input tabindex="-1">
<input id="input" type="text" />
</my-nput>
```
`tabbable()` should return an empty list for the example above
`tabbable()` returns a list which includes the input depicted above
This bug can cause a focus-trap to behave erratically when nearing the end of focusable elements.
<details>
<br/>
- Careful to test `typeof document/window !== 'undefined'` before …

fix: tabbable sometimes incorrectly includes children of a web component

---

.changeset/dull-wombats-approve.md
README.md
index.d.ts
src/index.js
test/e2e/focusable.cy.js
test/e2e/isFocusable.cy.js
test/e2e/isTabbable.cy.js
test/e2e/tabbable.cy.js

Fixes #666
Tabbable has long had legacy behavior that treated detached nodes as
visible. This commit makes the default/full `displayCheck` option
now behave correctly in that it treates detached nodes as hidden.
But since many people may depend on the buggy legacy behavior, a
new 'legacy-full' option is added which preserves the legacy
behavior, for now.
<details>
<br/>
- README updated (API …

[BREAKING][#666] Default full to attached nodes only; add legacy-full

---

.changeset/calm-toys-learn.md
src/index.js
test/e2e/shadow-dom.cy.js
test/fixtures/shadow-dom-query.html

Fixes #832
For shadow DOM support, we create internal objects with a `scope` property when looking for tabbable/focusable candidates. But when we sort the tabbable candidates, we look for an existing `scope` property assuming that HTMLElements don't have one, but it turns out `<th>` elements do have a `scope` attribute (and so `scope` property) and we mistake it for being a shadow DOM scope parent element. Crashing ensues.
So this just renames `CandidateScope.scope` to `CandidateScope.scopeParent` and adds a test to make sure things work as expected.
<details>
<br/>
- E2E test coverage …

[832] Fix bug with tabbable scoped table headers

---

.changeset/eight-bulldogs-shake.md
package.json
src/index.js

Fixes https://github.com/focus-trap/focus-trap-react/issues/905
There's a corner case where a node's `ownerDocument` could be null if
that node is itself the `document`, which could happen under special
circumstances.
<details>
<br/>
- Changeset added (run `yarn changeset` locally to add one, and follow the …

[ftr#905] Fix crash when ownerDocument is null

---

.changeset/pretty-moons-teach.md
.github/workflows/ci.yml
README.md
src/index.js
test/e2e/focusable.cy.js
test/e2e/isFocusable.cy.js
test/e2e/isTabbable.cy.js
test/e2e/shadow-dom.cy.js
test/e2e/tabbable.cy.js
test/fixtures/index.js
test/fixtures/inert.html
test/fixtures/shadow-dom-query.html

Fixes #292
Inert elements, as well as elements inside inert ancestors, will no longer be treated as tabbable/focusable.
Considering this a minor update since inert elements in browsers supporting the inert attribute (which has wide enough support now) would already be non-interactive. So this is tabbable catching to reality rather than tabbable altering behavior.
<details>
<br/>
- README …

[#292] Add support for inert attribute

---

.changeset/short-readers-suffer.md
package.json

Fixes #982
Tested locally by cloning this repo and then:
```
$ rm package-lock.json
$ npm install # regenerates package-lock.json
$ npm test # fails because of nwsapi issues post-v2.2.2
$ npm install # results in nwsapi@2.2.2
$ npm test # succeeds
```
<details>
<br/>
- Changeset added (run `npm run …

[#982] Pin nwsapi downstream jsdom dependency to v2.2.2

---

src/index.js

Per discussions in https://github.com/focus-trap/focus-trap/issues/375 and work in https://github.com/focus-trap/focus-trap/pull/974, we need to:
<details>
<br/>
- Changeset added (run `npm run changeset` locally to add one, and follow the prompts).
- EXCEPTION: A Changeset is not required if the change …

Make tabbable work with an array of elements

---

src/index.js

If the elements passed to `tabbable` are not ordered (by document order) the resulting order of tabbable elements would be incorrect because [sortByOrder](https://github.com/focus-trap/tabbable/blob/a5f9369d1ef93f394a7f8d64e93ceebb4d8a70f0/src/index.js#L545) only sorts the candidates by tab index.
The `.documentOrder` here: 
https://github.com/focus-trap/tabbable/blob/a5f9369d1ef93f394a7f8d64e93ceebb4d8a70f0/src/index.js#L241
Is merely the index of an element within the array of candidates: https://github.com/focus-trap/tabbable/blob/a5f9369d1ef93f394a7f8d64e93ceebb4d8a70f0/src/index.js#L559
Which is also a true indication of the relative document orders when the candidates are queried from a single element or from multiple elements sorted by document order.
I presume the reason for that …

Sort `containers` before querying candidates within them

---

.changeset/lovely-seals-burn.md
README.md
index.d.ts
src/index.js
test/fixtures/fixtures.js
test/fixtures/tabindex.html
test/unit/node.test.js
test/unit/unit.test.js

This is needed for https://github.com/focus-trap/focus-trap/pull/974 which will add support for positive tabindexes in focus-trap.
Also updates the docs/typings to make them more consistent and fix some broken links.
<details>
<br/>
- Changeset added (run `npm run changeset` locally to add one, and follow …

Add new getTabIndex() export

---

eslint.config.mjs
package-lock.json
package.json

Also make it more readable with less merging of objects for the `languageOptions`.
<details>
<br/>
- Web APIs introduced have __deep__ browser coverage, including Safari (often very late to adopt new APIs).
- Changeset added (run `npm run changeset` locally to add one, and follow the prompts).
- EXCEPTION: …

Fix ESLint 9 flat config issues
